// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCramUnFDi4-zCyEmbaSiDKpnrl2vTnV8g',
    appId: '1:134914734847:web:8d5f0a7d22e3352eb9aaca',
    messagingSenderId: '134914734847',
    projectId: 'library-book-search-app',
    authDomain: 'library-book-search-app.firebaseapp.com',
    storageBucket: 'library-book-search-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbmsWFsXlO-R3tcUVS7hJCJxLSghuAc0',
    appId: '1:134914734847:android:d186716faa6c3e78b9aaca',
    messagingSenderId: '134914734847',
    projectId: 'library-book-search-app',
    storageBucket: 'library-book-search-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_i20AA69LgDNhrLeoJ5XRnDtMlPAHB_s',
    appId: '1:134914734847:ios:91876a9592987c1ab9aaca',
    messagingSenderId: '134914734847',
    projectId: 'library-book-search-app',
    storageBucket: 'library-book-search-app.firebasestorage.app',
    iosBundleId: 'com.example.bookSearchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_i20AA69LgDNhrLeoJ5XRnDtMlPAHB_s',
    appId: '1:134914734847:ios:91876a9592987c1ab9aaca',
    messagingSenderId: '134914734847',
    projectId: 'library-book-search-app',
    storageBucket: 'library-book-search-app.firebasestorage.app',
    iosBundleId: 'com.example.bookSearchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCramUnFDi4-zCyEmbaSiDKpnrl2vTnV8g',
    appId: '1:134914734847:web:89338076b2fee76eb9aaca',
    messagingSenderId: '134914734847',
    projectId: 'library-book-search-app',
    authDomain: 'library-book-search-app.firebaseapp.com',
    storageBucket: 'library-book-search-app.firebasestorage.app',
  );
}
